# Insert or update a LottoRound entry
mutation UpsertLottoRound(
  $drwNo: Int!
  $drwNoDate: String!
  $totSellamnt: Int!
  $firstWinamnt: Int!
  $firstPrzwnerCo: Int!
  $drwtNo1: Int!
  $drwtNo2: Int!
  $drwtNo3: Int!
  $drwtNo4: Int!
  $drwtNo5: Int!
  $drwtNo6: Int!
  $bnusNo: Int!
  $returnValue: String!
) @auth(level: PUBLIC) {
  lottoRound_upsert(
    data: {
      drwNo: $drwNo
      drwNoDate: $drwNoDate
      totSellamnt: $totSellamnt
      firstWinamnt: $firstWinamnt
      firstPrzwnerCo: $firstPrzwnerCo
      drwtNo1: $drwtNo1
      drwtNo2: $drwtNo2
      drwtNo3: $drwtNo3
      drwtNo4: $drwtNo4
      drwtNo5: $drwtNo5
      drwtNo6: $drwtNo6
      bnusNo: $bnusNo
      returnValue: $returnValue
    }
  )
}
