type LottoRound @table(key: "drwNo") {
  drwNo: Int!
  drwNoDate: String!
  totSellamnt: Int!
  firstWinamnt: Int!
  firstPrzwnerCo: Int!
  drwtNo1: Int!
  drwtNo2: Int!
  drwtNo3: Int!
  drwtNo4: Int!
  drwtNo5: Int!
  drwtNo6: Int!
  bnusNo: Int!
  returnValue: String!
  createdAt: Date! @default(expr: "request.time")
}
